server:
  port: 8282


spring:
  application:
    name: clientapplication



eureka:
  instance:
    hostname: userclient
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#reportingservice:
#  ribbon:
#    eureka:
#      enabled: true
#    ServerListRefreshInterval: 15000
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList